name       : perl-term-readline-gnu
version    : 1.35
release    : 2
source     :
    - https://cpan.metacpan.org/authors/id/H/HA/HAYASHI/Term-ReadLine-Gnu-1.35.tar.gz : 575d32d4ab67cd656f314e8d0ee3d45d2491078f3b2421e520c4273e92eb9125
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Term::ReadLine::Gnu - Perl extension for the GNU Readline/History Library
description: |
    This is an implementation of Term::ReadLine using the GNU Readline/History Library. For basic functions object oriented interface is provided. These are described in the section "Standard Methods" and "Term::ReadLine::Gnu Functions". This package also has the interface with the almost all functions and variables which are documented in the GNU Readline/History Library Manual. They are documented in the section "Term::ReadLine::Gnu Functions" and "Term::ReadLine::Gnu Variables" briefly. For further details of the GNU Readline/History Library, see GNU Readline Library Manual and GNU History Library Manual.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
